services:
  - type: web
    name: automarket-frontend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    ports:
      - port: 80
    envVars:
      - key: NGINX_CONF
        value: nginx.conf

  - type: web
    name: automarket-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn backend.wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.7
